/**
 * This PlantUML diagram defines three interfaces - `ReprodutorMusical`, `AparelhoTelefonico`, and `NavegadorInternet` - and a class `Iphone` that implements these interfaces.
 * The `IPhone` class represents a smartphone that has the capabilities of a music player, a telephone, and a web browser.
 * The interfaces define example methods that the `IPhone` class must implement to provide these functionalities.
 */
@startuml IPhone

interface ReprodutorMusical {
    +tocar();
    +pausar();
    +selecionarMusica(String musica);
}

interface AparelhoTelefonico {
    +ligar(String numero);
    +atender();
    +iniciarCorreioVoz();
}

interface NavegadorInternet {
    +exibirPagina(String url);
    +adicionarNovaAba();
    +atualizarPagina();
}

class IPhone {}

IPhone -> ReprodutorMusical
IPhone -> AparelhoTelefonico
IPhone -> NavegadorInternet

@enduml